version: '3'
services:
  api:
    build: ./backend_node
    ports:
      - "3000:3000"
    volumes:
      - ./backend_node:/api
  client:
    build: ./client
    ports:
      - "3001:3001"
      - "38373:38373"
    volumes:
      - ./client:/client
  redis:
    image: "redis:alpine"